---
- name: Install software-properties-common
  apt: name=software-properties-common state=latest

- name: Add ansible repository
  apt_repository: repo='ppa:ansible/ansible'

- name: Install ansible
  apt: name=ansible state=latest

