---
- hosts: database
  become: true
  tasks:
    - name: Install MySQL
      apt: name=mysql-server update_cache=yes cache_valid_time=3600 state=present

    - name : ensure mysql started
      service: name=mysql state=started enabled=yes
