---
- hosts: loadbalancer
  become: true
  tasks:
    - name: verify nginx is running
      command: service nginx status

    - name: verify nginx listening on 80
      wait_for: port=80 timeout=3

- hosts: webserver
  become: true
  tasks:
    - name: verify apache2 is running
      command: service apache2 status

    - name: verify apache listening on 80
      wait_for: port=80 timeout=3

- hosts: database
  become: true
  tasks:
    - name: verify mysql is running
      command: service mysql status

    - name: verify mysql listening on 3306
      wait_for: port=3306 timeout=3

