---
- hosts: webserver
  become: true
  tasks:
    - name: install apache2
      apt: name={{ item }} state=present update_cache=yes cache_valid_time=3600
      with_items:
        - apache2
        - libapache2-mod-wsgi
        - python-pip
        - python-virtualenv
