---
- hosts: database
  become: true
  tasks:
    - name: Install MySQL
      apt: name=mysql-server update_cache=yes cache_valid_time=3600 state=present

    - name : ensure mysql started
      service: name=mysql state=started enabled=yes

    - name: ensure mysql is listening on all ports
      lineinfile: dest=/etc/mysql/my.cnf regexp=^bind-address line="bind-address = 0.0.0.0"
      notify: restart mysql

  handlers:
    - name: restart mysql
      service: name=mysql state=restarted
